### ISSUE TITLE
breaks PHPunit

### ISSUE THREAD

**Issue by matijakovacevic** [GlaivePro/Hidevara#1]
phpunit 8
laravel 5.8

Upon running PHPunit, throws

```php
PHP Fatal error:

Uncaught Illuminate\Contracts\Container\BindingResolutionException: 
Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.
```

**Comment by tontonsb** [comment]
Thanks for the report! Unfourtunately, I am not able to replicate the error. Can you provide some instructions on how to achieve this error in a fresh Laravel project?

I made a fresh laravel project, changed phpunit version to 8.0 in `composer.json`, did `composer update`. 

Required this package `composer require glaivepro/hidevara`.

Did `vendor/bin/phpunit` - no problem. Then I extended the handler in `bootstrap/app.php` and ran `vendor/bin/phpunit` succesfully once again.

**Comment by matijakovacevic** [comment]
my bad...forgot to extend it in `app/bootstrap`. thx :)

**Comment by Morinslash** [comment]
Hi,
I've hit same proble with PHPunit while using your package but only while testing http responses. I've tried to extend in bootstrap/app.php but didn't work.
Error message:

> PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/vagrant/code/MasterLaravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:962
> Stack trace:
> #0 /home/vagrant/code/MasterLaravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(796): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
> #1 /home/vagrant/code/MasterLaravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build('Illuminate\\Cont...')
> #2 /home/vagrant/code/MasterLaravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
> #3 /home/vagrant/code/MasterLaravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
> #4 /home/vagrant/code/MasterLaravel/vendor/laravel/framework/src/Illu in /home/vagrant/code/MasterLaravel/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 962
> PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/vagrant/code/MasterLaravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:962
> Stack trace:
> #0 /home/vagrant/code/MasterLaravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(796): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
> #1 /home/vagrant/code/MasterLaravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build('Illuminate\\Cont...')
> #2 /home/vagrant/code/MasterLaravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
> #3 /home/vagrant/code/MasterLaravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
> #4 /home/vagrant/code/MasterLaravel/vendor/laravel/framework/src/Illu in /home/vagrant/code/MasterLaravel/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 962

error occurs on testing that passed data to store route are invalid, here is simple test case:

> 
>  public function testStoreInvalidParams()
>     {
>         $params = [
>             'title' => 'x',
>             'content' => 'x',
>             '_token' => 'test'
>         ];
>         $this->withSession(['_token' => 'test'])
>             ->post('/posts', $params)
>             ->assertStatus(302)
>             ->assertSessionHas('errors');
>         $messages = session('errors')->getMessages();
>         $this->assertEquals($messages['title'][0], 'The title must be at least 5 characters.');
>         $this->assertEquals($messages['content'][0], 'The content must be at least 10 characters.');
>     }

**Comment by tontonsb** [comment]
Thank you for the thorough report! Thanks to yout test example I managed to recreate this issue.

**Comment by Morinslash** [comment]
All PHPunit works fine until you try to actually send invalid data and test web page response so it's not that easy to find until you do this, waiting for solution !

**Comment by tontonsb** [comment]
I could not find the actual problems. It seems that some of the providers are not registered at the moment where PHPUnit tries to instantiate an exception.

I found that it does not crash if `processIsolation="true"` is set in the `phpunit.xml` and added a tip in readme.

However, I don't think this package is really needed while running PHPUnit. So I disabled it by default when the environment is `testing` and drafted a new release. I also changed the instructions to register it in `bootstrap/app.php` with and `if ('testing' != env('APP_ENV'))`.

Please let me know if these fixes still don't solve your issues.

**Comment by Morinslash** [comment]
Workaround with 
`if ('testing' != env('APP_ENV'))`
works like a charm! Thanks!

`processIsolation="true"`
slow testing speed a lot so its not best solution but also works.
