### ISSUE TITLE
Maximum execution time exceeded /GlaivePro\Hidevara\HidingHandler@render

### ISSUE THREAD

**Issue by 4n70w4** [GlaivePro/Hidevara#4]
Maximum execution time of 30 seconds exceeded

![image](https://user-images.githubusercontent.com/38257723/83764884-27fc6380-a683-11ea-8bf4-e2458f0c3344.png)

**Comment by tontonsb** [comment]
That's surely a lot! Normally it should only go through the list of variables and replace some of them.

What were you doing? Is the expected error containing an extremely large dataset?

Does the problem disappear if you don't use this package? It could also be something nested within, i.e. the default handler.

**Comment by 4n70w4** [comment]
I disabled this package, you now need to wait a while to see results.

**Comment by 4n70w4** [comment]
Okay, now problem with `/App\Exceptions\Handler@render`


```php
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;

class Handler extends ExceptionHandler {
// ...
    public function render($request, Exception $exception) {
        return parent::render($request, $exception);
    }
```

**Comment by tontonsb** [comment]
Thanks for letting me know that!
